name: Publish Package
on:
  push:
    branches:
    - master
jobs:
  update_documentation:
    runs-on: ubuntu-latest
    name: Update Mixture documentation with DocFX
    steps:
    - uses: actions/checkout@v1
    # TODO: copy documentation package files to docfx folder
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docs/docfx/docfx.json
